<?php

declare(strict_types=1);

/**
 * ISO 4217 currency data for DefaultCurrencyRegistry.
 *
 * Symbols and display names are sourced from ICU (ext-intl) at build time;
 * minor units (scale) follow the official ISO 4217 standard (0-, 2-, 3-decimal
 * sets), which can differ from ICU's practical cash digits. Checked in as a static
 * dataset so the money package has NO runtime dependency on ext-intl.
 * Circulating currencies only — excludes precious metals, fund/bond and test codes.
 *
 * @return array<string, array{scale: int, symbol: string, name: string}>
 */

return [
    'AED' => ['scale' => 2, 'symbol' => 'AED', 'name' => 'United Arab Emirates Dirham'],
    'AFN' => ['scale' => 2, 'symbol' => 'AFN', 'name' => 'Afghan Afghani'],
    'ALL' => ['scale' => 2, 'symbol' => 'ALL', 'name' => 'Albanian Lek'],
    'AMD' => ['scale' => 2, 'symbol' => 'AMD', 'name' => 'Armenian Dram'],
    'ANG' => ['scale' => 2, 'symbol' => 'ANG', 'name' => 'Netherlands Antillean Guilder'],
    'AOA' => ['scale' => 2, 'symbol' => 'AOA', 'name' => 'Angolan Kwanza'],
    'ARS' => ['scale' => 2, 'symbol' => 'ARS', 'name' => 'Argentine Peso'],
    'AUD' => ['scale' => 2, 'symbol' => 'A$', 'name' => 'Australian Dollar'],
    'AWG' => ['scale' => 2, 'symbol' => 'AWG', 'name' => 'Aruban Florin'],
    'AZN' => ['scale' => 2, 'symbol' => 'AZN', 'name' => 'Azerbaijani Manat'],
    'BAM' => ['scale' => 2, 'symbol' => 'BAM', 'name' => 'Bosnia-Herzegovina Convertible Mark'],
    'BBD' => ['scale' => 2, 'symbol' => 'BBD', 'name' => 'Barbadian Dollar'],
    'BDT' => ['scale' => 2, 'symbol' => 'BDT', 'name' => 'Bangladeshi Taka'],
    'BGN' => ['scale' => 2, 'symbol' => 'BGN', 'name' => 'Bulgarian Lev'],
    'BHD' => ['scale' => 3, 'symbol' => 'BHD', 'name' => 'Bahraini Dinar'],
    'BIF' => ['scale' => 0, 'symbol' => 'BIF', 'name' => 'Burundian Franc'],
    'BMD' => ['scale' => 2, 'symbol' => 'BMD', 'name' => 'Bermudan Dollar'],
    'BND' => ['scale' => 2, 'symbol' => 'BND', 'name' => 'Brunei Dollar'],
    'BOB' => ['scale' => 2, 'symbol' => 'BOB', 'name' => 'Bolivian Boliviano'],
    'BRL' => ['scale' => 2, 'symbol' => 'R$', 'name' => 'Brazilian Real'],
    'BSD' => ['scale' => 2, 'symbol' => 'BSD', 'name' => 'Bahamian Dollar'],
    'BTN' => ['scale' => 2, 'symbol' => 'BTN', 'name' => 'Bhutanese Ngultrum'],
    'BWP' => ['scale' => 2, 'symbol' => 'BWP', 'name' => 'Botswanan Pula'],
    'BYN' => ['scale' => 2, 'symbol' => 'BYN', 'name' => 'Belarusian Ruble'],
    'BZD' => ['scale' => 2, 'symbol' => 'BZD', 'name' => 'Belize Dollar'],
    'CAD' => ['scale' => 2, 'symbol' => 'CA$', 'name' => 'Canadian Dollar'],
    'CDF' => ['scale' => 2, 'symbol' => 'CDF', 'name' => 'Congolese Franc'],
    'CHF' => ['scale' => 2, 'symbol' => 'CHF', 'name' => 'Swiss Franc'],
    'CLP' => ['scale' => 0, 'symbol' => 'CLP', 'name' => 'Chilean Peso'],
    'CNY' => ['scale' => 2, 'symbol' => 'CN¥', 'name' => 'Chinese Yuan'],
    'COP' => ['scale' => 2, 'symbol' => 'COP', 'name' => 'Colombian Peso'],
    'CRC' => ['scale' => 2, 'symbol' => 'CRC', 'name' => 'Costa Rican Colón'],
    'CUP' => ['scale' => 2, 'symbol' => 'CUP', 'name' => 'Cuban Peso'],
    'CVE' => ['scale' => 2, 'symbol' => 'CVE', 'name' => 'Cape Verdean Escudo'],
    'CZK' => ['scale' => 2, 'symbol' => 'CZK', 'name' => 'Czech Koruna'],
    'DJF' => ['scale' => 0, 'symbol' => 'DJF', 'name' => 'Djiboutian Franc'],
    'DKK' => ['scale' => 2, 'symbol' => 'DKK', 'name' => 'Danish Krone'],
    'DOP' => ['scale' => 2, 'symbol' => 'DOP', 'name' => 'Dominican Peso'],
    'DZD' => ['scale' => 2, 'symbol' => 'DZD', 'name' => 'Algerian Dinar'],
    'EGP' => ['scale' => 2, 'symbol' => 'EGP', 'name' => 'Egyptian Pound'],
    'ERN' => ['scale' => 2, 'symbol' => 'ERN', 'name' => 'Eritrean Nakfa'],
    'ETB' => ['scale' => 2, 'symbol' => 'ETB', 'name' => 'Ethiopian Birr'],
    'EUR' => ['scale' => 2, 'symbol' => '€', 'name' => 'Euro'],
    'FJD' => ['scale' => 2, 'symbol' => 'FJD', 'name' => 'Fijian Dollar'],
    'FKP' => ['scale' => 2, 'symbol' => 'FKP', 'name' => 'Falkland Islands Pound'],
    'GBP' => ['scale' => 2, 'symbol' => '£', 'name' => 'British Pound'],
    'GEL' => ['scale' => 2, 'symbol' => 'GEL', 'name' => 'Georgian Lari'],
    'GHS' => ['scale' => 2, 'symbol' => 'GHS', 'name' => 'Ghanaian Cedi'],
    'GIP' => ['scale' => 2, 'symbol' => 'GIP', 'name' => 'Gibraltar Pound'],
    'GMD' => ['scale' => 2, 'symbol' => 'GMD', 'name' => 'Gambian Dalasi'],
    'GNF' => ['scale' => 0, 'symbol' => 'GNF', 'name' => 'Guinean Franc'],
    'GTQ' => ['scale' => 2, 'symbol' => 'GTQ', 'name' => 'Guatemalan Quetzal'],
    'GYD' => ['scale' => 2, 'symbol' => 'GYD', 'name' => 'Guyanaese Dollar'],
    'HKD' => ['scale' => 2, 'symbol' => 'HK$', 'name' => 'Hong Kong Dollar'],
    'HNL' => ['scale' => 2, 'symbol' => 'HNL', 'name' => 'Honduran Lempira'],
    'HTG' => ['scale' => 2, 'symbol' => 'HTG', 'name' => 'Haitian Gourde'],
    'HUF' => ['scale' => 2, 'symbol' => 'HUF', 'name' => 'Hungarian Forint'],
    'IDR' => ['scale' => 2, 'symbol' => 'IDR', 'name' => 'Indonesian Rupiah'],
    'ILS' => ['scale' => 2, 'symbol' => '₪', 'name' => 'Israeli New Shekel'],
    'INR' => ['scale' => 2, 'symbol' => '₹', 'name' => 'Indian Rupee'],
    'IQD' => ['scale' => 3, 'symbol' => 'IQD', 'name' => 'Iraqi Dinar'],
    'IRR' => ['scale' => 2, 'symbol' => 'IRR', 'name' => 'Iranian Rial'],
    'ISK' => ['scale' => 0, 'symbol' => 'ISK', 'name' => 'Icelandic Króna'],
    'JMD' => ['scale' => 2, 'symbol' => 'JMD', 'name' => 'Jamaican Dollar'],
    'JOD' => ['scale' => 3, 'symbol' => 'JOD', 'name' => 'Jordanian Dinar'],
    'JPY' => ['scale' => 0, 'symbol' => '¥', 'name' => 'Japanese Yen'],
    'KES' => ['scale' => 2, 'symbol' => 'KES', 'name' => 'Kenyan Shilling'],
    'KGS' => ['scale' => 2, 'symbol' => 'KGS', 'name' => 'Kyrgystani Som'],
    'KHR' => ['scale' => 2, 'symbol' => 'KHR', 'name' => 'Cambodian Riel'],
    'KMF' => ['scale' => 0, 'symbol' => 'KMF', 'name' => 'Comorian Franc'],
    'KPW' => ['scale' => 2, 'symbol' => 'KPW', 'name' => 'North Korean Won'],
    'KRW' => ['scale' => 0, 'symbol' => '₩', 'name' => 'South Korean Won'],
    'KWD' => ['scale' => 3, 'symbol' => 'KWD', 'name' => 'Kuwaiti Dinar'],
    'KYD' => ['scale' => 2, 'symbol' => 'KYD', 'name' => 'Cayman Islands Dollar'],
    'KZT' => ['scale' => 2, 'symbol' => 'KZT', 'name' => 'Kazakhstani Tenge'],
    'LAK' => ['scale' => 2, 'symbol' => 'LAK', 'name' => 'Laotian Kip'],
    'LBP' => ['scale' => 2, 'symbol' => 'LBP', 'name' => 'Lebanese Pound'],
    'LKR' => ['scale' => 2, 'symbol' => 'LKR', 'name' => 'Sri Lankan Rupee'],
    'LRD' => ['scale' => 2, 'symbol' => 'LRD', 'name' => 'Liberian Dollar'],
    'LSL' => ['scale' => 2, 'symbol' => 'LSL', 'name' => 'Lesotho Loti'],
    'LYD' => ['scale' => 3, 'symbol' => 'LYD', 'name' => 'Libyan Dinar'],
    'MAD' => ['scale' => 2, 'symbol' => 'MAD', 'name' => 'Moroccan Dirham'],
    'MDL' => ['scale' => 2, 'symbol' => 'MDL', 'name' => 'Moldovan Leu'],
    'MGA' => ['scale' => 2, 'symbol' => 'MGA', 'name' => 'Malagasy Ariary'],
    'MKD' => ['scale' => 2, 'symbol' => 'MKD', 'name' => 'Macedonian Denar'],
    'MMK' => ['scale' => 2, 'symbol' => 'MMK', 'name' => 'Myanmar Kyat'],
    'MNT' => ['scale' => 2, 'symbol' => 'MNT', 'name' => 'Mongolian Tugrik'],
    'MOP' => ['scale' => 2, 'symbol' => 'MOP', 'name' => 'Macanese Pataca'],
    'MRU' => ['scale' => 2, 'symbol' => 'MRU', 'name' => 'Mauritanian Ouguiya'],
    'MUR' => ['scale' => 2, 'symbol' => 'MUR', 'name' => 'Mauritian Rupee'],
    'MVR' => ['scale' => 2, 'symbol' => 'MVR', 'name' => 'Maldivian Rufiyaa'],
    'MWK' => ['scale' => 2, 'symbol' => 'MWK', 'name' => 'Malawian Kwacha'],
    'MXN' => ['scale' => 2, 'symbol' => 'MX$', 'name' => 'Mexican Peso'],
    'MYR' => ['scale' => 2, 'symbol' => 'MYR', 'name' => 'Malaysian Ringgit'],
    'MZN' => ['scale' => 2, 'symbol' => 'MZN', 'name' => 'Mozambican Metical'],
    'NAD' => ['scale' => 2, 'symbol' => 'NAD', 'name' => 'Namibian Dollar'],
    'NGN' => ['scale' => 2, 'symbol' => 'NGN', 'name' => 'Nigerian Naira'],
    'NIO' => ['scale' => 2, 'symbol' => 'NIO', 'name' => 'Nicaraguan Córdoba'],
    'NOK' => ['scale' => 2, 'symbol' => 'NOK', 'name' => 'Norwegian Krone'],
    'NPR' => ['scale' => 2, 'symbol' => 'NPR', 'name' => 'Nepalese Rupee'],
    'NZD' => ['scale' => 2, 'symbol' => 'NZ$', 'name' => 'New Zealand Dollar'],
    'OMR' => ['scale' => 3, 'symbol' => 'OMR', 'name' => 'Omani Rial'],
    'PAB' => ['scale' => 2, 'symbol' => 'PAB', 'name' => 'Panamanian Balboa'],
    'PEN' => ['scale' => 2, 'symbol' => 'PEN', 'name' => 'Peruvian Sol'],
    'PGK' => ['scale' => 2, 'symbol' => 'PGK', 'name' => 'Papua New Guinean Kina'],
    'PHP' => ['scale' => 2, 'symbol' => '₱', 'name' => 'Philippine Peso'],
    'PKR' => ['scale' => 2, 'symbol' => 'PKR', 'name' => 'Pakistani Rupee'],
    'PLN' => ['scale' => 2, 'symbol' => 'PLN', 'name' => 'Polish Zloty'],
    'PYG' => ['scale' => 0, 'symbol' => 'PYG', 'name' => 'Paraguayan Guarani'],
    'QAR' => ['scale' => 2, 'symbol' => 'QAR', 'name' => 'Qatari Riyal'],
    'RON' => ['scale' => 2, 'symbol' => 'RON', 'name' => 'Romanian Leu'],
    'RSD' => ['scale' => 2, 'symbol' => 'RSD', 'name' => 'Serbian Dinar'],
    'RUB' => ['scale' => 2, 'symbol' => 'RUB', 'name' => 'Russian Ruble'],
    'RWF' => ['scale' => 0, 'symbol' => 'RWF', 'name' => 'Rwandan Franc'],
    'SAR' => ['scale' => 2, 'symbol' => 'SAR', 'name' => 'Saudi Riyal'],
    'SBD' => ['scale' => 2, 'symbol' => 'SBD', 'name' => 'Solomon Islands Dollar'],
    'SCR' => ['scale' => 2, 'symbol' => 'SCR', 'name' => 'Seychellois Rupee'],
    'SDG' => ['scale' => 2, 'symbol' => 'SDG', 'name' => 'Sudanese Pound'],
    'SEK' => ['scale' => 2, 'symbol' => 'SEK', 'name' => 'Swedish Krona'],
    'SGD' => ['scale' => 2, 'symbol' => 'SGD', 'name' => 'Singapore Dollar'],
    'SHP' => ['scale' => 2, 'symbol' => 'SHP', 'name' => 'St. Helena Pound'],
    'SLE' => ['scale' => 2, 'symbol' => 'SLE', 'name' => 'Sierra Leonean Leone'],
    'SOS' => ['scale' => 2, 'symbol' => 'SOS', 'name' => 'Somali Shilling'],
    'SRD' => ['scale' => 2, 'symbol' => 'SRD', 'name' => 'Surinamese Dollar'],
    'SSP' => ['scale' => 2, 'symbol' => 'SSP', 'name' => 'South Sudanese Pound'],
    'STN' => ['scale' => 2, 'symbol' => 'STN', 'name' => 'São Tomé & Príncipe Dobra'],
    'SVC' => ['scale' => 2, 'symbol' => 'SVC', 'name' => 'Salvadoran Colón'],
    'SYP' => ['scale' => 2, 'symbol' => 'SYP', 'name' => 'Syrian Pound'],
    'SZL' => ['scale' => 2, 'symbol' => 'SZL', 'name' => 'Swazi Lilangeni'],
    'THB' => ['scale' => 2, 'symbol' => 'THB', 'name' => 'Thai Baht'],
    'TJS' => ['scale' => 2, 'symbol' => 'TJS', 'name' => 'Tajikistani Somoni'],
    'TMT' => ['scale' => 2, 'symbol' => 'TMT', 'name' => 'Turkmenistani Manat'],
    'TND' => ['scale' => 3, 'symbol' => 'TND', 'name' => 'Tunisian Dinar'],
    'TOP' => ['scale' => 2, 'symbol' => 'TOP', 'name' => 'Tongan Paʻanga'],
    'TRY' => ['scale' => 2, 'symbol' => 'TRY', 'name' => 'Turkish Lira'],
    'TTD' => ['scale' => 2, 'symbol' => 'TTD', 'name' => 'Trinidad & Tobago Dollar'],
    'TWD' => ['scale' => 2, 'symbol' => 'NT$', 'name' => 'New Taiwan Dollar'],
    'TZS' => ['scale' => 2, 'symbol' => 'TZS', 'name' => 'Tanzanian Shilling'],
    'UAH' => ['scale' => 2, 'symbol' => 'UAH', 'name' => 'Ukrainian Hryvnia'],
    'UGX' => ['scale' => 0, 'symbol' => 'UGX', 'name' => 'Ugandan Shilling'],
    'USD' => ['scale' => 2, 'symbol' => '$', 'name' => 'US Dollar'],
    'UYU' => ['scale' => 2, 'symbol' => 'UYU', 'name' => 'Uruguayan Peso'],
    'UZS' => ['scale' => 2, 'symbol' => 'UZS', 'name' => 'Uzbekistani Som'],
    'VED' => ['scale' => 2, 'symbol' => 'VED', 'name' => 'Bolívar Soberano'],
    'VES' => ['scale' => 2, 'symbol' => 'VES', 'name' => 'Venezuelan Bolívar'],
    'VND' => ['scale' => 0, 'symbol' => '₫', 'name' => 'Vietnamese Dong'],
    'VUV' => ['scale' => 0, 'symbol' => 'VUV', 'name' => 'Vanuatu Vatu'],
    'WST' => ['scale' => 2, 'symbol' => 'WST', 'name' => 'Samoan Tala'],
    'XAF' => ['scale' => 0, 'symbol' => 'FCFA', 'name' => 'Central African CFA Franc'],
    'XCD' => ['scale' => 2, 'symbol' => 'EC$', 'name' => 'East Caribbean Dollar'],
    'XOF' => ['scale' => 0, 'symbol' => 'F CFA', 'name' => 'West African CFA Franc'],
    'XPF' => ['scale' => 0, 'symbol' => 'CFPF', 'name' => 'CFP Franc'],
    'YER' => ['scale' => 2, 'symbol' => 'YER', 'name' => 'Yemeni Rial'],
    'ZAR' => ['scale' => 2, 'symbol' => 'ZAR', 'name' => 'South African Rand'],
    'ZMW' => ['scale' => 2, 'symbol' => 'ZMW', 'name' => 'Zambian Kwacha'],
    'ZWG' => ['scale' => 2, 'symbol' => 'ZWG', 'name' => 'Zimbabwean Gold'],
];
