// Hand-maintained module-load list. Unlike packages/frontend-demo/resources/js/.generated/extensions.ts
// (which the vite-plugin-markommerce scanner overwrites on every dev-server start),
// THIS file is NOT regenerated by any tool. Update it by hand when a new package
// is added to the markommerce module chain. The file lives at the top of resources/js
// (not under .generated/) precisely to signal this hand-maintained status to future
// maintainers — anything inside .generated/ is owned by the scanner plugin.

import '@markommerce/frontend';
import '@markommerce/theme-blank';
import '@markommerce/theme-blank-demo';

export const LOADED_MODULES = [
  { name: '@markommerce/frontend', priority: 0 },
  { name: '@markommerce/theme-blank', priority: 100 },
  { name: '@markommerce/theme-blank-demo', priority: 1010 },
] as const;
